### ISSUE TITLE
"DLL load failed" error.

### ISSUE THREAD

**Issue by ahmetanildindar** [komoot/staticmap#16]
Dear all,
I have an interesting problem :) 
I'm very happy about the staticmap in my humble Python codes for earthquake mapping. 

Recently I've started havin problem importing staticmap. Below is the warning message I receive. I've checked the PIL and found that it is installed. But "ImportError: DLL load failed: The specified module could not be found." does not ignite anything to this folk :)

> >>> import staticmap
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\ProgramData\Anaconda3\lib\site-packages\staticmap\__init__.py", line 1, in <module>
>     from .staticmap import StaticMap, CircleMarker, IconMarker, Line, Polygon
>   File "C:\ProgramData\Anaconda3\lib\site-packages\staticmap\staticmap.py", line 6, in <module>
>     from PIL import Image, ImageDraw
>   File "C:\ProgramData\Anaconda3\lib\site-packages\PIL\Image.py", line 58, in <module>
>     from . import _imaging as core
> ImportError: DLL load failed: The specified module could not be found.
> >>>

Is there anyone out there with a solution/recommendation?

Best regards from Istanbul.

++Ahmet

**Comment by ahmetanildindar** [comment]
I've solved problem by using below;
`conda unistall pillow`
and then
`pip install pillow`

For my case, the recent version of PILLOW through Conda created the DLL problem.
